matrix:
  include:
    - os: linux
      language: java
      sudo: false # for faster builds
      jdk: openjdk11
    - os: osx
      language: java
      sudo: false # for faster builds
      jdk: openjdk11
    - os: windows
      language: shell # 'java' not supported, 'generic' causes VM to hang on boot.
      sudo: false # for faster builds
before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install -y openjdk --version 11.0
      export JAVA_HOME="/c/Program Files/OpenJDK/jdk-11"
      export PATH="$JAVA_HOME/bin:$PATH"
      export GRADLE_OPTS=-Dorg.gradle.daemon=false
    fi
script:
  - chmod +x subdirectories_build.sh
  - ./subdirectories_build.sh
