language: shell
jdk:
  - oraclejdk8
os:
  - windows
  - linux
  - osx
script:
  - choco install jdk8
  - export JAVA_HOME=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin"
  - java -version
  - chmod +x subdirectories_build.sh
  - ./subdirectories_build.sh
