language: shell
jdk:
  - oraclejdk8
os:
  - windows
  - linux
  - osx
script:
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; choco install jdk8; fi
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_201/bin"; fi
  - chmod +x subdirectories_build.sh
  - ./subdirectories_build.sh
